/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/satellite-dishes-animation-fun-72393f67ee5b4e17bc64cd18b443dd4d
Title: Satellite Dishes Animation Fun
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Satelite = (props) => {
    
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/satellite_dishes_animation_fun.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Play the first animation (if any)
    if (actions) {
      const animationKeys = Object.keys(actions);
      if (animationKeys.length > 0) {
        actions[animationKeys[0]].reset().fadeIn(0.5).play();
      }
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null} scale={[0.5, 0.5, 0.5]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Satellite_dish_Blender_Internal_render79fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Plane" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Plane_unnamed_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_unnamed_0.geometry}
                    material={materials.unnamed}
                  />
                </group>
                <group
                  name="Circle_029"
                  position={[-3.559, 0.376, -0.008]}
                  rotation={[-Math.PI / 2, -0.785, 2.618]}
                  scale={0.618}>
                  <mesh
                    name="Circle_029_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_029_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003}
                  />
                </group>
                <group
                  name="Circle_002"
                  position={[-0.008, 0.738, 0.002]}
                  rotation={[-1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_002_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_002_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_012"
                  position={[-0.008, 0.376, 3.559]}
                  rotation={[-0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_012_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_012_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_011"
                  position={[-0.008, -0.738, -0.002]}
                  rotation={[1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_011_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_011_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_006" position={[0, -0.738, 0]} rotation={[1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_006_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_006_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_007" position={[0, -0.925, 0]} rotation={[1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_007_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_007_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_009" position={[0, -3.111, 0.001]} rotation={[1.57, 0, -2.094]}>
                  <mesh
                    name="Circle_009_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_009_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_008" position={[0, -1.926, 0]} rotation={[1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_008_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_008_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_044"
                  position={[0, -2.111, 5.206]}
                  rotation={[0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_044_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_044_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_045"
                  position={[0, -1.274, 4.368]}
                  rotation={[0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_045_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_045_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_042"
                  position={[-0.008, -0.435, 3.527]}
                  rotation={[0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_042_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_042_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_047"
                  position={[0, -0.434, 3.528]}
                  rotation={[0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_047_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_047_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_046" position={[0, -0.566, 3.66]} rotation={[0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_046_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_046_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_041"
                  position={[3.527, -0.435, 0.008]}
                  rotation={[Math.PI / 2, 0.785, 2.618]}>
                  <mesh
                    name="Circle_041_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_041_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_036"
                  position={[3.528, -0.434, 0]}
                  rotation={[Math.PI / 2, 0.785, 2.618]}>
                  <mesh
                    name="Circle_036_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_036_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_059"
                  position={[0, -0.434, -3.528]}
                  rotation={[2.356, 0, -2.094]}>
                  <mesh
                    name="Circle_059_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_059_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_054"
                  position={[-0.008, -0.433, -3.529]}
                  rotation={[2.356, 0, -2.094]}>
                  <mesh
                    name="Circle_054_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_054_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_058"
                  position={[0, -0.566, -3.66]}
                  rotation={[2.356, 0, -2.094]}>
                  <mesh
                    name="Circle_058_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_058_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_056"
                  position={[0, -2.112, -5.205]}
                  rotation={[2.356, 0, -2.094]}>
                  <mesh
                    name="Circle_056_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_056_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_057"
                  position={[0, -1.274, -4.368]}
                  rotation={[2.356, 0, -2.094]}>
                  <mesh
                    name="Circle_057_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_057_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_048"
                  position={[-3.528, -0.434, 0]}
                  rotation={[Math.PI / 2, -0.785, -0.523]}>
                  <mesh
                    name="Circle_048_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_048_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_053"
                  position={[-3.527, -0.435, -0.008]}
                  rotation={[Math.PI / 2, -0.785, -0.523]}>
                  <mesh
                    name="Circle_053_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_053_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_049"
                  position={[-3.66, -0.566, 0]}
                  rotation={[Math.PI / 2, -0.786, -0.523]}>
                  <mesh
                    name="Circle_049_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_049_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_051"
                  position={[-5.206, -2.111, 0]}
                  rotation={[Math.PI / 2, -0.786, -0.523]}>
                  <mesh
                    name="Circle_051_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_051_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_050"
                  position={[-4.368, -1.274, 0]}
                  rotation={[Math.PI / 2, -0.786, -0.523]}>
                  <mesh
                    name="Circle_050_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_050_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_005" position={[0, 0.738, 0]} rotation={[-1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_005_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_005_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_004" position={[0, 0.925, 0]} rotation={[-1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_004_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_004_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_003" position={[0, 1.926, 0]} rotation={[-1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_003_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_003_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_018"
                  position={[0, 0.385, -3.561]}
                  rotation={[-2.367, 0, -2.094]}>
                  <mesh
                    name="Circle_018_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_018_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_023"
                  position={[-0.008, 0.387, -3.56]}
                  rotation={[-2.367, 0, -2.094]}>
                  <mesh
                    name="Circle_023_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_023_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_021"
                  position={[0, 2.044, -5.258]}
                  rotation={[-2.368, 0, -2.094]}>
                  <mesh
                    name="Circle_021_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_021_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_019"
                  position={[0, 0.516, -3.694]}
                  rotation={[-2.367, 0, -2.094]}>
                  <mesh
                    name="Circle_019_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_019_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_024"
                  position={[-3.558, 0.377, 0]}
                  rotation={[-Math.PI / 2, -0.785, 2.618]}>
                  <mesh
                    name="Circle_024_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_024_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_025"
                  position={[-3.69, 0.509, 0]}
                  rotation={[-Math.PI / 2, -0.785, 2.618]}>
                  <mesh
                    name="Circle_025_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_025_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_026"
                  position={[-4.398, 1.218, 0]}
                  rotation={[-Math.PI / 2, -0.785, 2.618]}>
                  <mesh
                    name="Circle_026_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_026_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_027"
                  position={[-5.235, 2.056, 0]}
                  rotation={[-Math.PI / 2, -0.785, 2.618]}>
                  <mesh
                    name="Circle_027_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_027_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_017"
                  position={[0, 0.377, 3.558]}
                  rotation={[-0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_017_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_017_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_016" position={[0, 0.509, 3.69]} rotation={[-0.786, 0, -2.094]}>
                  <mesh
                    name="Circle_016_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_016_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_015"
                  position={[0, 1.218, 4.398]}
                  rotation={[-0.786, 0, -2.094]}>
                  <mesh
                    name="Circle_015_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_015_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_014"
                  position={[0, 2.056, 5.235]}
                  rotation={[-0.786, 0, -2.094]}>
                  <mesh
                    name="Circle_014_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_014_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_030"
                  position={[3.559, 0.376, 0.008]}
                  rotation={[-Math.PI / 2, 0.785, -0.523]}>
                  <mesh
                    name="Circle_030_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_030_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_035"
                  position={[3.558, 0.377, 0]}
                  rotation={[-Math.PI / 2, 0.785, -0.523]}>
                  <mesh
                    name="Circle_035_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_035_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_032"
                  position={[5.235, 2.056, 0]}
                  rotation={[-Math.PI / 2, 0.785, -0.523]}>
                  <mesh
                    name="Circle_032_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_032_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_034"
                  position={[3.69, 0.509, 0]}
                  rotation={[-Math.PI / 2, 0.785, -0.523]}>
                  <mesh
                    name="Circle_034_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_034_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_033"
                  position={[4.398, 1.218, 0]}
                  rotation={[-Math.PI / 2, 0.785, -0.523]}>
                  <mesh
                    name="Circle_033_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_033_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_037"
                  position={[3.66, -0.566, 0]}
                  rotation={[Math.PI / 2, 0.786, 2.618]}>
                  <mesh
                    name="Circle_037_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_037_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_039"
                  position={[5.206, -2.111, 0]}
                  rotation={[Math.PI / 2, 0.786, 2.618]}>
                  <mesh
                    name="Circle_039_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_039_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_038"
                  position={[4.368, -1.274, 0]}
                  rotation={[Math.PI / 2, 0.786, 2.618]}>
                  <mesh
                    name="Circle_038_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_038_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_040"
                  position={[5.268, -2.173, 0]}
                  rotation={[Math.PI / 2, 0.786, 2.619]}>
                  <mesh
                    name="Circle_040_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_040_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_020"
                  position={[0, 1.216, -4.41]}
                  rotation={[-2.368, 0, -2.094]}>
                  <mesh
                    name="Circle_020_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_020_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_055"
                  position={[0, -2.174, -5.267]}
                  rotation={[2.356, 0, -2.094]}>
                  <mesh
                    name="Circle_055_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_055_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_052"
                  position={[-5.268, -2.173, 0]}
                  rotation={[Math.PI / 2, -0.786, -0.523]}>
                  <mesh
                    name="Circle_052_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_052_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group name="Circle_010" position={[0, -3.199, 0.001]} rotation={[1.57, 0, -2.094]}>
                  <mesh
                    name="Circle_010_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_010_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_043"
                  position={[0, -2.173, 5.268]}
                  rotation={[0.785, 0, -2.094]}>
                  <mesh
                    name="Circle_043_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_043_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_001"
                  position={[0, 3.111, -0.001]}
                  rotation={[-1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_001_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_001_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_000"
                  position={[0, 3.199, -0.001]}
                  rotation={[-1.571, 0, -2.094]}>
                  <mesh
                    name="Circle_000_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_000_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_028"
                  position={[-5.297, 2.118, 0]}
                  rotation={[-Math.PI / 2, -0.785, 2.619]}>
                  <mesh
                    name="Circle_028_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_028_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_013"
                  position={[0, 2.118, 5.297]}
                  rotation={[-0.786, 0, -2.094]}>
                  <mesh
                    name="Circle_013_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_013_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_031"
                  position={[5.297, 2.118, 0]}
                  rotation={[-Math.PI / 2, 0.785, -0.523]}>
                  <mesh
                    name="Circle_031_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_031_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Circle_022"
                  position={[0, 2.105, -5.32]}
                  rotation={[-2.368, 0, -2.094]}>
                  <mesh
                    name="Circle_022_Material_013__untitled_003_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle_022_Material_013__untitled_003_0.geometry}
                    material={materials.Material_013__untitled_003_0}
                  />
                </group>
                <group
                  name="Sun"
                  position={[1.856, 5.958, 1.239]}
                  rotation={[0.121, -0.124, -0.446]}>
                  <group name="Object_127" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_128" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/satellite_dishes_animation_fun.glb')

export default Satelite